openapi: 3.0.3
info:
  title: payment-service
  description: This is a payment-service API.
  version: 1.0.0
servers:
  - url: http://localhost:8081/api/v1/payment
    description: Local server
paths:
  /history:
    get:
      summary: Retrieve a history of transactions
      responses:
        '200':
          description: A description of transactions
          content:
            application/json:
              schema:
                type: string
  /pay:
    post:
      summary: Perfom a new payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentModel'
      responses:
        '200':
          description: A payment for a product
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    PaymentModel:
      type: object
      properties:
        product:
          type: string
          example: "123"
        amount:
          type: number
          format: float
          example: 2000.00
        user:
          type: string
          example: "123"
