openapi: 3.0.3
info:
  title: stock-service
  description: This is a stock-service API.
  version: 1.0.0
servers:
  - url: http://localhost:8083/api/v1/stock
    description: Local server
paths:
  /debit:
    post:
      summary: Perfom a stock debit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductModel'
      responses:
        '200':
          description: A list of StockModel
          content:
            application/json:
              schema:
                type: array
                format: StockModel
components:
  schemas:
    ProductModel:
      type: object
      properties:
        id:
          type: string
          example: "123"
        name:
          type: string
          example: "123"
        price:
          type: number
          format: float
          example: 2000.00
        qtd:
          type: integer
          example: 2
