openapi: 3.0.3
info:
  title: supplier-service
  description: This is a supplier-service API.
  version: 1.0.0
servers:
  - url: http://localhost:8084/api/v1/supplier
    description: Local server
paths:
  /all:
    get:
      summary: Retrieve all suppliers
      responses:
        '200':
          description: A list of SupplierModel
          content:
            application/json:
              schema:
                type: array
                format: SupplierModel
components:
  schemas:
    SupplierModel:
      type: object
      properties:
        id:
          type: string
          example: "123"
        name:
          type: string
          example: "Game Vision LTD"
