openapi: 3.0.3
info:
  title: user-service
  description: This is a user-service API.
  version: 1.0.0
servers:
  - url: http://localhost:8085/api/v1/user
    description: Local server
paths:
  /all:
    get:
      summary: Retrieve all users
      responses:
        '200':
          description: A list of UserModel
          content:
            application/json:
              schema:
                type: array
                format: UserModel
components:
  schemas:
    SupplierModel:
      type: object
      properties:
        id:
          type: string
          example: "123"
        name:
          type: string
          example: "Charles Dove"
